#ifndef MODEL_MODULE_KIND_H
#define MODEL_MODULE_KIND_H

typedef enum {
	MODULE_KIND_UNKNOWN,
	MODULE_KIND_DI_8,
	MODULE_KIND_DI_16,
	MODULE_KIND_DI_32,
	MODULE_KIND_DO_8,
	MODULE_KIND_DO_16,
	MODULE_KIND_DO_32
} module_kind_t;

#endif

